<a href="https://colab.research.google.com/github/Danielmzm081199/IntroalaIA/blob/main/Lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init, inspect; init.init(force_download=False); init.get_weblink()

In [ ]:
from local.lib.rlxmoocapi import submit, session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.02", varname="student");

logging in as daniel.munozm@udea.edu.co... please wait
using course session ai4eng.v1.udea.r3::2024.1
success!! you are logged in


#*Metrics*

In [ ]:
import numpy as np

# Generar los datos de prueba
t1_actual = np.random.randint(2, size=20)
t1_predicted = np.abs(t1_actual * (np.random.random(size=20) > (np.random.random() * 0.9 + 0.05)).astype(int))

# Contar las predicciones correctas
predicciones_correctas = np.sum(t1_actual == t1_predicted)

# Calcular el porcentaje de precisión
porcentaje_precision = (predicciones_correctas / len(t1_actual)) * 100

# Redondear el resultado a tres decimales
accuracy = round(porcentaje_precision, 3)

# Imprimir los resultados
print("actual    :", ", ".join([str(i) for i in t1_actual]))
print("predicted :", ", ".join([str(i) for i in t1_predicted]))
print("Precisión :", accuracy, "%")


actual    : 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0
predicted : 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0
Precisión : 80.0 %


In [ ]:
accuracy = 0.80

In [ ]:
# student.submit_task(globals(), task_id="task_01");

In [ ]:
import numpy as np

# Generar los datos de prueba
t2_predicted = np.random.randint(2, size=20)
t2_actual = np.random.randint(2, size=20)
t2_predicted[np.argwhere(t2_actual==1)[0][0]] = 0

# Calcular verdaderos positivos (TP) y falsos negativos (FN)
TP = np.sum((t2_predicted == 1) & (t2_actual == 1))
FN = np.sum((t2_predicted == 0) & (t2_actual == 1))

# Calcular sensibilidad
sensibilidad = TP / (TP + FN)

# Imprimir los resultados
print("actual    :", ", ".join([str(i) for i in t2_actual]))
print("predicted :", ", ".join([str(i) for i in t2_predicted]))
print("Sensibilidad (tasa de verdaderos positivos o tasa de recuperación) :", sensibilidad)


actual    : 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1
predicted : 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1
Sensibilidad (tasa de verdaderos positivos o tasa de recuperación) : 0.5


In [ ]:
tpr = 0.50

In [ ]:
# student.submit_task(globals(), task_id="task_02");

In [ ]:
import numpy as np

# Función para calcular el error logarítmico cuadrático medio
def rmsle(y_actual, y_pred):
    return np.sqrt(np.mean(np.square(np.log1p(y_pred) - np.log1p(y_actual))))

# Generar los datos de prueba
t3_actual = np.random.randint(80, size=15) + 20
t3_predicted = np.random.randint(80, size=15) + 20

# Calcular el RMSLE
error_rmsle = rmsle(t3_actual, t3_predicted)

# Imprimir los resultados
print("actual    :", t3_actual)
print("predicted :", t3_predicted)
print("Error RMSLE:", error_rmsle)


actual    : [80 54 62 63 23 85 61 80 49 71 92 32 56 91 65]
predicted : [99 54 50 84 36 33 69 82 28 20 71 90 36 41 35]
Error RMSLE: 0.5950760916518099


In [ ]:
rmsle = 0.59

In [ ]:
# student.submit_task(globals(), task_id="task_03");

In [ ]:
import numpy as np

# Función para calcular la pérdida logarítmica multiclase
def multiclass_log_loss(y_true, y_pred):
    epsilon = 1e-15  # Valor pequeño para evitar divisiones por cero
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)  # Ajuste de valores para evitar log(0)
    return -np.mean(np.sum(y_true * np.log(y_pred), axis=1))

# Generar datos de prueba
t4_predicted = np.random.random(size=(7,5)).T + 0.5
t4_predicted = np.round((t4_predicted / np.sum(t4_predicted, axis=0)), 2).T

t4_actual = np.eye(5)[np.random.randint(5, size=len(t4_predicted))].astype(int)

print("actual")
print(t4_actual)
print("\npredicted")
print(t4_predicted)

# Calcular la pérdida logarítmica multiclase
loss = multiclass_log_loss(t4_actual, t4_predicted)

# Imprimir la pérdida
print("\nPérdida logarítmica multiclase:", loss)


actual
[[0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]]

predicted
[[0.2  0.21 0.12 0.26 0.21]
 [0.21 0.16 0.14 0.23 0.25]
 [0.18 0.13 0.28 0.21 0.2 ]
 [0.16 0.24 0.15 0.16 0.3 ]
 [0.18 0.25 0.12 0.27 0.18]
 [0.2  0.13 0.18 0.25 0.24]
 [0.2  0.34 0.16 0.14 0.16]]

Pérdida logarítmica multiclase: 1.744741301083608


In [ ]:
logloss = 1.74

In [ ]:
# student.submit_task(globals(), task_id="task_04");