<a href="https://colab.research.google.com/github/Danielmzm081199/IntroalaIA/blob/main/Lab1_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()

In [ ]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

logging in as daniel.munozm@udea.edu.co... please wait
using course session ai4eng.v1.udea.r3::2024.1
success!! you are logged in



#*Suma de Matrices*

In [ ]:
import numpy as np

# Las matrices quedan almacenadas en las variables s y t
s = np.array([2,7,3])
t = np.array([4,3,6])

#Creamos la funcion con el nombre suma_matrices
def suma_matrices(a,b):

   result = a + b
   return result

suma_matrices(s,t)


array([ 6, 10,  9])

#*Prueba Manualmente*

In [ ]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print("\nCodigo Hecho:")
print (suma_matrices(a,b))

[[6 5]
 [4 1]
 [8 6]]
[[2 3]
 [5 1]
 [2 8]]

Codigo Hecho:
[[ 8  8]
 [ 9  2]
 [10 14]]


#*Registro de respuesta*

In [ ]:
student.submit_task(globals(), task_id="task_01");

#*Realiza Calculo Promedio Numero Aleatorios*

In [ ]:
import numpy as np

rlist = np.random.randint(100, size=10)
rlist

array([77,  4, 95, 84, 92, 54,  0, 98, 66, 46])

*En este caso usare de la libreria numpy el mean que es la media o promedio*

In [ ]:
avg = np.mean(rlist)
print(avg)

61.6



#*Registro de Respuesta*



In [ ]:
student.submit_task(globals(), task_id="task_02");