<a href="https://colab.research.google.com/github/Danielmzm081199/IntroalaIA/blob/main/LabsNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()

replicating local resources


In [2]:
from local.lib.rlxmoocapi import submit, session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L02.02", varname="student");

logging in as daniel.munozm@udea.edu.co... please wait
using course session ai4eng.v1.udea.r3::2024.1
success!! you are logged in


In [8]:
import numpy as np

def cauchy(x, y):
    r = np.zeros((len(x), len(y)))
    r += 1.0 / (x[:, np.newaxis] - y)
    if np.any(np.isinf(r)):
        raise ValueError("Se encontró una división entre cero.")
    return r

# Ejemplo de uso:
x = np.array([45, 31, 67, 75, 54])
y = np.array([17,  7, 15, 15, 18])
resultado = cauchy(x, y)
print(resultado)


[[0.03571429 0.02631579 0.03333333 0.03333333 0.03703704]
 [0.07142857 0.04166667 0.0625     0.0625     0.07692308]
 [0.02       0.01666667 0.01923077 0.01923077 0.02040816]
 [0.01724138 0.01470588 0.01666667 0.01666667 0.01754386]
 [0.02702703 0.0212766  0.02564103 0.02564103 0.02777778]]


In [9]:
student.submit_task(globals(), task_id="task_01");

In [10]:
import numpy as np

def minimo(x, v):
    # Calcula la diferencia absoluta entre cada elemento de x y v
    diferencias = np.abs(x - v)
    # Encuentra la posición del elemento con la mínima diferencia
    posicion_minima = np.argmin(diferencias)
    return posicion_minima

# Ejemplo de uso:
x = np.array([1, 5, 9, 15, 20])
v = 12
posicion = minimo(x, v)
print("El elemento más cercano a", v, "en el vector x se encuentra en la posición:", posicion)


El elemento más cercano a 12 en el vector x se encuentra en la posición: 2


In [11]:
student.submit_task(globals(), task_id="task_02");

In [12]:
import numpy as np

def media(X):
    # Calcula la media de cada fila de la matriz X
    medias_filas = np.mean(X, axis=1, keepdims=True)
    # Resta la media de cada fila de la matriz X a cada componente de la fila respectiva
    nueva_matriz = X - medias_filas
    return nueva_matriz

# Ejemplo de uso:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

resultado = media(X)
print(resultado)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [13]:
student.submit_task(globals(), task_id="task_03");

In [22]:
import numpy as np

def doublediag(X):
    return X + np.eye(X.shape[0]) * np.diag(X)[:, np.newaxis]

# Ejemplo de uso:
X = np.array([[79, 45, 67,  8, 37],
              [47, 40,  5, 79, 86],
              [72, 25, 44, 45, 22],
              [12, 85,  8, 53, 28],
              [ 4, 37, 36, 40, 16]])

resultado = doublediag(X)
print(resultado)


[[158.  45.  67.   8.  37.]
 [ 47.  80.   5.  79.  86.]
 [ 72.  25.  88.  45.  22.]
 [ 12.  85.   8. 106.  28.]
 [  4.  37.  36.  40.  32.]]


In [23]:
student.submit_task(globals(), task_id="task_04");